// File: lib/firebase_options.dart
// This file is typically generated by the FlutterFire CLI
// You should run `flutterfire configure` to generate this file properly

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // IMPORTANT: Replace these placeholder values with your actual Firebase configuration
  // You should get these from your google-services.json and GoogleService-Info.plist

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5cMeBc-uIfngbnrUiQyqYv5qp09dlEA',
    appId: '1:508275127448:web:6782f0fc6bd21c27664ced',
    messagingSenderId: '508275127448',
    projectId: 'agritech-22',
    authDomain: 'agritech-22.firebaseapp.com',
    storageBucket: 'agritech-22.firebasestorage.app',
    measurementId: 'G-C1C28XEG7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHzS_G8j_LzDIU9Oig53XnoOBrKGspZ4',
    appId: '1:508275127448:android:241da0309fb6fce0664ced',
    messagingSenderId: '508275127448',
    projectId: 'agritech-22',
    storageBucket: 'agritech-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7scAKmUv7-DglwJMuzsxvsEEJJA25ko',
    appId: '1:508275127448:ios:9b9aa2555c0c90b2664ced',
    messagingSenderId: '508275127448',
    projectId: 'agritech-22',
    storageBucket: 'agritech-22.firebasestorage.app',
    iosBundleId: 'com.example.loginFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7scAKmUv7-DglwJMuzsxvsEEJJA25ko',
    appId: '1:508275127448:ios:9b9aa2555c0c90b2664ced',
    messagingSenderId: '508275127448',
    projectId: 'agritech-22',
    storageBucket: 'agritech-22.firebasestorage.app',
    iosBundleId: 'com.example.loginFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs5cMeBc-uIfngbnrUiQyqYv5qp09dlEA',
    appId: '1:508275127448:web:03139d784005a934664ced',
    messagingSenderId: '508275127448',
    projectId: 'agritech-22',
    authDomain: 'agritech-22.firebaseapp.com',
    storageBucket: 'agritech-22.firebasestorage.app',
    measurementId: 'G-W37HHLTSBG',
  );

}